export const categoryProducts = {
  "combo-offer": {
    title: "কম্বো অফার",
    description:
      "Special combo offers with multiple products at discounted prices",
    products: [
      {
        id: 101,
        name: "Diabetes Care Combo",
        description: "Complete diabetes management combo",
        category: "combo-offer",
        brand: "Nature Cure Food",
        originalPrice: 1500,
        discountedPrice: 1200,
        discount: 20,
        stockStatus: "In Stock",
        image: "/assets/products/product-1.png",
        rating: 4.8,
        totalReviews: 156,
        salesCount: 2847,
        ratingDistribution: { 5: 120, 4: 25, 3: 8, 2: 2, 1: 1 },
        comboItems: ["Dibadex 100mg", "Diabetes Support", "Sugar Control"],
      },
      {
        id: 102,
        name: "Heart Health Combo",
        description: "Complete heart health package",
        category: "combo-offer",
        brand: "Nature Cure Food",
        originalPrice: 2000,
        discountedPrice: 1600,
        discount: 20,
        stockStatus: "In Stock",
        image: "/assets/products/product-2.png",
        rating: 4.9,
        totalReviews: 89,
        salesCount: 1523,
        ratingDistribution: { 5: 75, 4: 12, 3: 2, 2: 0, 1: 0 },
        comboItems: ["Heart Support", "Cardio Care", "Blood Pressure Control"],
      },
      {
        id: 103,
        name: "Liver Care Combo",
        description: "Complete liver health package",
        category: "combo-offer",
        brand: "Nature Cure Food",
        originalPrice: 1800,
        discountedPrice: 1440,
        discount: 20,
        stockStatus: "In Stock",
        image: "/assets/products/product-3.png",
        rating: 4.7,
        totalReviews: 203,
        salesCount: 3421,
        ratingDistribution: { 5: 150, 4: 35, 3: 15, 2: 2, 1: 1 },
        comboItems: ["Liver Support", "Detox Formula", "Liver Cleanse"],
      },
      {
        id: 104,
        name: "Weight Loss Combo",
        description: "Complete weight management package",
        category: "combo-offer",
        brand: "Nature Cure Food",
        originalPrice: 2200,
        discountedPrice: 1760,
        discount: 20,
        stockStatus: "In Stock",
        image: "/assets/products/product-4.png",
        rating: 4.6,
        totalReviews: 312,
        salesCount: 4187,
        ratingDistribution: { 5: 200, 4: 75, 3: 30, 2: 5, 1: 2 },
        comboItems: ["Weight Loss", "Metabolism Boost", "Fat Burner"],
      },
      {
        id: 105,
        name: "Allergy Relief Combo",
        description: "Complete allergy management package",
        category: "combo-offer",
        brand: "Nature Cure Food",
        originalPrice: 1600,
        discountedPrice: 1280,
        discount: 20,
        stockStatus: "In Stock",
        image: "/assets/products/product-5.png",
        rating: 4.5,
        totalReviews: 178,
        salesCount: 2654,
        ratingDistribution: { 5: 120, 4: 40, 3: 15, 2: 2, 1: 1 },
        comboItems: ["Allergy Relief", "Anti-Histamine", "Immune Support"],
      },
    ],
  },
  "herbal-medicine": {
    title: "হার্টের ঔষধ",
    description: "Herbal medicines for heart health and cardiovascular support",
    products: [
      {
        id: 201,
        name: "Heart Support Capsules",
        description: "Natural heart health support",
        category: "herbal-medicine",
        brand: "Herbal Plus",
        originalPrice: 450,
        discountedPrice: 405,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-1.png",
        rating: 4.8,
        totalReviews: 234,
        salesCount: 3421,
        ratingDistribution: { 5: 180, 4: 35, 3: 15, 2: 3, 1: 1 },
      },
      {
        id: 202,
        name: "Cardio Care Tablets",
        description: "Cardiovascular health support",
        category: "herbal-medicine",
        brand: "Herbal Plus",
        originalPrice: 500,
        discountedPrice: 450,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-2.png",
        rating: 4.7,
        totalReviews: 189,
        salesCount: 2876,
        ratingDistribution: { 5: 140, 4: 35, 3: 10, 2: 3, 1: 1 },
      },
      {
        id: 203,
        name: "Blood Pressure Control",
        description: "Natural blood pressure management",
        category: "herbal-medicine",
        brand: "Herbal Plus",
        originalPrice: 400,
        discountedPrice: 360,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-3.png",
        rating: 4.9,
        totalReviews: 312,
        salesCount: 4567,
        ratingDistribution: { 5: 250, 4: 45, 3: 15, 2: 1, 1: 1 },
      },
      {
        id: 204,
        name: "Heart Tonic Syrup",
        description: "Traditional heart tonic",
        category: "herbal-medicine",
        brand: "Herbal Plus",
        originalPrice: 350,
        discountedPrice: 315,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-4.png",
        rating: 4.6,
        totalReviews: 156,
        salesCount: 2134,
        ratingDistribution: { 5: 110, 4: 30, 3: 12, 2: 3, 1: 1 },
      },
      {
        id: 205,
        name: "Circulation Support",
        description: "Improves blood circulation",
        category: "herbal-medicine",
        brand: "Herbal Plus",
        originalPrice: 380,
        discountedPrice: 342,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-5.png",
        rating: 4.8,
        totalReviews: 267,
        salesCount: 3891,
        ratingDistribution: { 5: 200, 4: 45, 3: 18, 2: 3, 1: 1 },
      },
      {
        id: 206,
        name: "Heart Wellness Tea",
        description: "Herbal tea for heart health",
        category: "herbal-medicine",
        brand: "Herbal Plus",
        originalPrice: 250,
        discountedPrice: 225,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-6.png",
        rating: 4.5,
        totalReviews: 145,
        salesCount: 1876,
        ratingDistribution: { 5: 100, 4: 30, 3: 12, 2: 2, 1: 1 },
      },
    ],
  },
  dazabaties: {
    title: "ডায়াবেটিস",
    description: "Diabetes management and blood sugar control medicines",
    products: [
      {
        id: 301,
        name: "Dibadex 100mg",
        description: "Diabetes management tablet",
        category: "dazabaties",
        brand: "Diabetes Care",
        originalPrice: 500,
        discountedPrice: 450,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-1.png",
        rating: 4.7,
        totalReviews: 456,
        salesCount: 6789,
        ratingDistribution: { 5: 320, 4: 95, 3: 30, 2: 8, 1: 3 },
      },
      {
        id: 302,
        name: "Sugar Control Plus",
        description: "Advanced sugar control formula",
        category: "dazabaties",
        brand: "Diabetes Care",
        originalPrice: 600,
        discountedPrice: 540,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-2.png",
        rating: 4.8,
        totalReviews: 389,
        salesCount: 5432,
        ratingDistribution: { 5: 280, 4: 75, 3: 25, 2: 7, 1: 2 },
      },
      {
        id: 303,
        name: "Glucose Balance",
        description: "Natural glucose balancing",
        category: "dazabaties",
        brand: "Diabetes Care",
        originalPrice: 450,
        discountedPrice: 405,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-3.png",
        rating: 4.6,
        totalReviews: 267,
        salesCount: 3891,
        ratingDistribution: { 5: 180, 4: 60, 3: 20, 2: 5, 1: 2 },
      },
      {
        id: 304,
        name: "Insulin Support",
        description: "Natural insulin support",
        category: "dazabaties",
        brand: "Diabetes Care",
        originalPrice: 550,
        discountedPrice: 495,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-4.png",
        rating: 4.9,
        totalReviews: 523,
        salesCount: 7654,
        ratingDistribution: { 5: 400, 4: 85, 3: 30, 2: 6, 1: 2 },
      },
      {
        id: 305,
        name: "Diabetes Care Tea",
        description: "Herbal tea for diabetes",
        category: "dazabaties",
        brand: "Diabetes Care",
        originalPrice: 300,
        discountedPrice: 270,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-5.png",
        rating: 4.5,
        totalReviews: 189,
        salesCount: 2765,
        ratingDistribution: { 5: 130, 4: 40, 3: 15, 2: 3, 1: 1 },
      },
      {
        id: 306,
        name: "Blood Sugar Monitor",
        description: "Natural blood sugar support",
        category: "dazabaties",
        brand: "Diabetes Care",
        originalPrice: 400,
        discountedPrice: 360,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-6.png",
        rating: 4.7,
        totalReviews: 234,
        salesCount: 3421,
        ratingDistribution: { 5: 170, 4: 45, 3: 15, 2: 3, 1: 1 },
      },
    ],
  },
  "high-presenter": {
    title: "হাই প্রেশার",
    description: "High blood pressure management and control medicines",
    products: [
      {
        id: 401,
        name: "BP Control Plus",
        description: "Advanced blood pressure control",
        category: "high-presenter",
        brand: "BP Care",
        originalPrice: 480,
        discountedPrice: 432,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-1.png",
        rating: 4.8,
        totalReviews: 345,
        salesCount: 4987,
        ratingDistribution: { 5: 250, 4: 65, 3: 25, 2: 3, 1: 2 },
      },
      {
        id: 402,
        name: "Hypertension Relief",
        description: "Natural hypertension relief",
        category: "high-presenter",
        brand: "BP Care",
        originalPrice: 420,
        discountedPrice: 378,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-2.png",
        rating: 4.7,
        totalReviews: 278,
        salesCount: 4032,
        ratingDistribution: { 5: 190, 4: 60, 3: 20, 2: 6, 1: 2 },
      },
      {
        id: 403,
        name: "Cardio Pressure",
        description: "Cardiovascular pressure control",
        category: "high-presenter",
        brand: "BP Care",
        originalPrice: 520,
        discountedPrice: 468,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-3.png",
        rating: 4.9,
        totalReviews: 412,
        salesCount: 5987,
        ratingDistribution: { 5: 320, 4: 70, 3: 18, 2: 3, 1: 1 },
      },
      {
        id: 404,
        name: "Blood Pressure Tea",
        description: "Herbal tea for blood pressure",
        category: "high-presenter",
        brand: "BP Care",
        originalPrice: 280,
        discountedPrice: 252,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-4.png",
        rating: 4.6,
        totalReviews: 156,
        salesCount: 2134,
        ratingDistribution: { 5: 110, 4: 30, 3: 12, 2: 3, 1: 1 },
      },
      {
        id: 405,
        name: "Pressure Normalizer",
        description: "Natural pressure normalization",
        category: "high-presenter",
        brand: "BP Care",
        originalPrice: 450,
        discountedPrice: 405,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-5.png",
        rating: 4.8,
        totalReviews: 289,
        salesCount: 4123,
        ratingDistribution: { 5: 210, 4: 55, 3: 20, 2: 3, 1: 1 },
      },
    ],
  },
  "livar-medicine": {
    title: "লিভারের ঔষধ",
    description: "Liver health and detoxification medicines",
    products: [
      {
        id: 501,
        name: "Liver Support Plus",
        description: "Advanced liver support formula",
        category: "livar-medicine",
        brand: "Liver Care",
        originalPrice: 550,
        discountedPrice: 495,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-1.png",
        rating: 4.8,
        totalReviews: 423,
        salesCount: 6123,
        ratingDistribution: { 5: 310, 4: 75, 3: 30, 2: 6, 1: 2 },
      },
      {
        id: 502,
        name: "Detox Formula",
        description: "Natural liver detoxification",
        category: "livar-medicine",
        brand: "Liver Care",
        originalPrice: 480,
        discountedPrice: 432,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-2.png",
        rating: 4.7,
        totalReviews: 356,
        salesCount: 4987,
        ratingDistribution: { 5: 250, 4: 70, 3: 25, 2: 8, 1: 3 },
      },
      {
        id: 503,
        name: "Liver Cleanse",
        description: "Complete liver cleansing",
        category: "livar-medicine",
        brand: "Liver Care",
        originalPrice: 420,
        discountedPrice: 378,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-3.png",
        rating: 4.9,
        totalReviews: 489,
        salesCount: 7234,
        ratingDistribution: { 5: 380, 4: 75, 3: 25, 2: 7, 1: 2 },
      },
      {
        id: 504,
        name: "Hepatoprotective",
        description: "Liver protection formula",
        category: "livar-medicine",
        brand: "Liver Care",
        originalPrice: 500,
        discountedPrice: 450,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-4.png",
        rating: 4.8,
        totalReviews: 312,
        salesCount: 4567,
        ratingDistribution: { 5: 230, 4: 55, 3: 20, 2: 5, 1: 2 },
      },
      {
        id: 505,
        name: "Liver Tonic",
        description: "Traditional liver tonic",
        category: "livar-medicine",
        brand: "Liver Care",
        originalPrice: 380,
        discountedPrice: 342,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-5.png",
        rating: 4.6,
        totalReviews: 234,
        salesCount: 3421,
        ratingDistribution: { 5: 170, 4: 45, 3: 15, 2: 3, 1: 1 },
      },
      {
        id: 506,
        name: "Fatty Liver Care",
        description: "Fatty liver management",
        category: "livar-medicine",
        brand: "Liver Care",
        originalPrice: 520,
        discountedPrice: 468,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-6.png",
        rating: 4.8,
        totalReviews: 267,
        salesCount: 3891,
        ratingDistribution: { 5: 200, 4: 45, 3: 18, 2: 3, 1: 1 },
      },
    ],
  },
  "weight-loss": {
    title: "ওজন হ্রাস",
    description: "Weight loss and metabolism boosting medicines",
    products: [
      {
        id: 601,
        name: "Weight Loss Plus",
        description: "Advanced weight loss formula",
        category: "weight-loss",
        brand: "Slim Care",
        originalPrice: 600,
        discountedPrice: 540,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-1.png",
        rating: 4.7,
        totalReviews: 567,
        salesCount: 8234,
        ratingDistribution: { 5: 400, 4: 120, 3: 35, 2: 10, 1: 2 },
      },
      {
        id: 602,
        name: "Fat Burner",
        description: "Natural fat burning formula",
        category: "weight-loss",
        brand: "Slim Care",
        originalPrice: 550,
        discountedPrice: 495,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-2.png",
        rating: 4.8,
        totalReviews: 423,
        salesCount: 6123,
        ratingDistribution: { 5: 310, 4: 75, 3: 30, 2: 6, 1: 2 },
      },
      {
        id: 603,
        name: "Metabolism Boost",
        description: "Boosts metabolism naturally",
        category: "weight-loss",
        brand: "Slim Care",
        originalPrice: 480,
        discountedPrice: 432,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-3.png",
        rating: 4.6,
        totalReviews: 345,
        salesCount: 4987,
        ratingDistribution: { 5: 240, 4: 70, 3: 25, 2: 8, 1: 2 },
      },
      {
        id: 604,
        name: "Appetite Control",
        description: "Natural appetite suppression",
        category: "weight-loss",
        brand: "Slim Care",
        originalPrice: 450,
        discountedPrice: 405,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-4.png",
        rating: 4.9,
        totalReviews: 489,
        salesCount: 7234,
        ratingDistribution: { 5: 380, 4: 75, 3: 25, 2: 7, 1: 2 },
      },
      {
        id: 605,
        name: "Slimming Tea",
        description: "Herbal slimming tea",
        category: "weight-loss",
        brand: "Slim Care",
        originalPrice: 320,
        discountedPrice: 288,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-5.png",
        rating: 4.5,
        totalReviews: 234,
        salesCount: 3421,
        ratingDistribution: { 5: 170, 4: 45, 3: 15, 2: 3, 1: 1 },
      },
      {
        id: 606,
        name: "Body Shaper",
        description: "Complete body shaping",
        category: "weight-loss",
        brand: "Slim Care",
        originalPrice: 520,
        discountedPrice: 468,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-6.png",
        rating: 4.7,
        totalReviews: 312,
        salesCount: 4567,
        ratingDistribution: { 5: 230, 4: 55, 3: 20, 2: 5, 1: 2 },
      },
    ],
  },
  "elarji-medicine": {
    title: "এলার্জি ঔষধ",
    description: "Allergy relief and immune system support medicines",
    products: [
      {
        id: 701,
        name: "Allergy Relief",
        description: "Natural allergy relief formula",
        category: "elarji-medicine",
        brand: "Allergy Care",
        originalPrice: 380,
        discountedPrice: 342,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-1.png",
        rating: 4.7,
        totalReviews: 234,
        salesCount: 3421,
        ratingDistribution: { 5: 170, 4: 45, 3: 15, 2: 3, 1: 1 },
      },
      {
        id: 702,
        name: "Anti-Histamine",
        description: "Natural antihistamine formula",
        category: "elarji-medicine",
        brand: "Allergy Care",
        originalPrice: 420,
        discountedPrice: 378,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-2.png",
        rating: 4.8,
        totalReviews: 289,
        salesCount: 4123,
        ratingDistribution: { 5: 210, 4: 55, 3: 20, 2: 3, 1: 1 },
      },
      {
        id: 703,
        name: "Immune Support",
        description: "Immune system support",
        category: "elarji-medicine",
        brand: "Allergy Care",
        originalPrice: 450,
        discountedPrice: 405,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-3.png",
        rating: 4.6,
        totalReviews: 267,
        salesCount: 3891,
        ratingDistribution: { 5: 190, 4: 50, 3: 20, 2: 5, 1: 2 },
      },
      {
        id: 704,
        name: "Seasonal Allergy",
        description: "Seasonal allergy relief",
        category: "elarji-medicine",
        brand: "Allergy Care",
        originalPrice: 400,
        discountedPrice: 360,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-4.png",
        rating: 4.9,
        totalReviews: 356,
        salesCount: 4987,
        ratingDistribution: { 5: 280, 4: 50, 3: 20, 2: 4, 1: 2 },
      },
      {
        id: 705,
        name: "Skin Allergy Relief",
        description: "Skin allergy treatment",
        category: "elarji-medicine",
        brand: "Allergy Care",
        originalPrice: 350,
        discountedPrice: 315,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-5.png",
        rating: 4.5,
        totalReviews: 189,
        salesCount: 2765,
        ratingDistribution: { 5: 130, 4: 40, 3: 15, 2: 3, 1: 1 },
      },
      {
        id: 706,
        name: "Respiratory Support",
        description: "Respiratory allergy support",
        category: "elarji-medicine",
        brand: "Allergy Care",
        originalPrice: 480,
        discountedPrice: 432,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-6.png",
        rating: 4.7,
        totalReviews: 312,
        salesCount: 4567,
        ratingDistribution: { 5: 230, 4: 55, 3: 20, 2: 5, 1: 2 },
      },
    ],
  },
  "secretary-problems": {
    title: "গোপন সমস্যার",
    description: "Private health and intimate wellness medicines",
    products: [
      {
        id: 801,
        name: "Men's Health Plus",
        description: "Complete men's health support",
        category: "secretary-problems",
        brand: "Private Care",
        originalPrice: 650,
        discountedPrice: 585,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-1.png",
        rating: 4.8,
        totalReviews: 189,
        salesCount: 2765,
        ratingDistribution: { 5: 140, 4: 35, 3: 10, 2: 3, 1: 1 },
      },
      {
        id: 802,
        name: "Women's Wellness",
        description: "Women's intimate health",
        category: "secretary-problems",
        brand: "Private Care",
        originalPrice: 580,
        discountedPrice: 522,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-2.png",
        rating: 4.7,
        totalReviews: 156,
        salesCount: 2134,
        ratingDistribution: { 5: 110, 4: 30, 3: 12, 2: 3, 1: 1 },
      },
      {
        id: 803,
        name: "Intimate Care",
        description: "Intimate health support",
        category: "secretary-problems",
        brand: "Private Care",
        originalPrice: 520,
        discountedPrice: 468,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-3.png",
        rating: 4.9,
        totalReviews: 234,
        salesCount: 3421,
        ratingDistribution: { 5: 180, 4: 35, 3: 15, 2: 3, 1: 1 },
      },
      {
        id: 804,
        name: "Private Wellness",
        description: "Private health formula",
        category: "secretary-problems",
        brand: "Private Care",
        originalPrice: 480,
        discountedPrice: 432,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-4.png",
        rating: 4.6,
        totalReviews: 145,
        salesCount: 1876,
        ratingDistribution: { 5: 100, 4: 30, 3: 12, 2: 2, 1: 1 },
      },
      {
        id: 805,
        name: "Intimate Support",
        description: "Intimate health support",
        category: "secretary-problems",
        brand: "Private Care",
        originalPrice: 450,
        discountedPrice: 405,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-5.png",
        rating: 4.8,
        totalReviews: 267,
        salesCount: 3891,
        ratingDistribution: { 5: 200, 4: 45, 3: 18, 2: 3, 1: 1 },
      },
    ],
  },
  medicines: {
    title: "মেডিসিন",
    description: "General medicines and health supplements",
    products: [
      {
        id: 901,
        name: "Multivitamin Plus",
        description: "Complete multivitamin formula",
        category: "medicines",
        brand: "General Health",
        originalPrice: 400,
        discountedPrice: 360,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-1.png",
        rating: 4.8,
        totalReviews: 567,
        salesCount: 8234,
        ratingDistribution: { 5: 400, 4: 120, 3: 35, 2: 10, 1: 2 },
      },
      {
        id: 902,
        name: "Calcium Supplement",
        description: "High potency calcium",
        category: "medicines",
        brand: "General Health",
        originalPrice: 350,
        discountedPrice: 315,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-2.png",
        rating: 4.7,
        totalReviews: 423,
        salesCount: 6123,
        ratingDistribution: { 5: 310, 4: 75, 3: 30, 2: 6, 1: 2 },
      },
      {
        id: 903,
        name: "Iron Supplement",
        description: "Natural iron supplement",
        category: "medicines",
        brand: "General Health",
        originalPrice: 320,
        discountedPrice: 288,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-3.png",
        rating: 4.6,
        totalReviews: 345,
        salesCount: 4987,
        ratingDistribution: { 5: 240, 4: 70, 3: 25, 2: 8, 1: 2 },
      },
      {
        id: 904,
        name: "Vitamin D3",
        description: "High potency Vitamin D3",
        category: "medicines",
        brand: "General Health",
        originalPrice: 380,
        discountedPrice: 342,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-4.png",
        rating: 4.9,
        totalReviews: 489,
        salesCount: 7234,
        ratingDistribution: { 5: 380, 4: 75, 3: 25, 2: 7, 1: 2 },
      },
      {
        id: 905,
        name: "Omega-3",
        description: "Fish oil omega-3",
        category: "medicines",
        brand: "General Health",
        originalPrice: 450,
        discountedPrice: 405,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-5.png",
        rating: 4.8,
        totalReviews: 312,
        salesCount: 4567,
        ratingDistribution: { 5: 230, 4: 55, 3: 20, 2: 5, 1: 2 },
      },
      {
        id: 906,
        name: "Probiotics",
        description: "Digestive health probiotics",
        category: "medicines",
        brand: "General Health",
        originalPrice: 420,
        discountedPrice: 378,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-6.png",
        rating: 4.7,
        totalReviews: 234,
        salesCount: 3421,
        ratingDistribution: { 5: 170, 4: 45, 3: 15, 2: 3, 1: 1 },
      },
      {
        id: 907,
        name: "Joint Support",
        description: "Joint health support",
        category: "medicines",
        brand: "General Health",
        originalPrice: 480,
        discountedPrice: 432,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-1.png",
        rating: 4.8,
        totalReviews: 289,
        salesCount: 4123,
        ratingDistribution: { 5: 210, 4: 55, 3: 20, 2: 3, 1: 1 },
      },
      {
        id: 908,
        name: "Memory Support",
        description: "Brain and memory support",
        category: "medicines",
        brand: "General Health",
        originalPrice: 520,
        discountedPrice: 468,
        discount: 10,
        stockStatus: "In Stock",
        image: "/assets/products/product-2.png",
        rating: 4.9,
        totalReviews: 356,
        salesCount: 4987,
        ratingDistribution: { 5: 280, 4: 50, 3: 20, 2: 4, 1: 2 },
      },
    ],
  },
};
