export const staticProducts = [
  {
    id: 1,
    name: "Dibedex",
    description: "(ডায়াবিডেক্স) 500 mg",
    category: "Herbal-Index Medicine",
    originalPrice: 550,
    discountedPrice: 450,
    discount: "20% OFF",
    stockStatus: "In Stock",
    image: "/assets/products/product-1.png",
    images: [
      "/assets/products/product-1.png",
      "/assets/products/product-2.png",
      "/assets/products/product-3.png",
      "/assets/products/product-4.png",
    ],
    rating: 4.5,
    totalReviews: 127,
    salesCount: 2847,
    ratingDistribution: {
      5: 89,
      4: 23,
      3: 10,
      2: 3,
      1: 2,
    },
  },
  {
    id: 2,
    name: "Conture Plus medicine",
    category: "Herbal-Index Medicine",
    originalPrice: 550,
    discountedPrice: 450,
    discount: "20% OFF",
    stockStatus: "In Stock",
    image: "/assets/products/product-2.png",
    images: [
      "/assets/products/product-2.png",
      "/assets/products/product-1.png",
      "/assets/products/product-3.png",
      "/assets/products/product-5.png",
    ],
    rating: 4.2,
    totalReviews: 89,
    salesCount: 1923,
    ratingDistribution: {
      5: 56,
      4: 20,
      3: 8,
      2: 3,
      1: 2,
    },
  },
  {
    id: 3,
    name: "G-Cosef Medicine (450 ML)",
    category: "Herbal-Index Medicine",
    originalPrice: 1100,
    discountedPrice: 910,
    discount: "20% OFF",
    stockStatus: "In Stock",
    image: "/assets/products/product-3.png",
    images: [
      "/assets/products/product-3.png",
      "/assets/products/product-1.png",
      "/assets/products/product-2.png",
      "/assets/products/product-6.png",
    ],
    rating: 4.8,
    totalReviews: 203,
    salesCount: 4532,
    ratingDistribution: {
      5: 165,
      4: 28,
      3: 7,
      2: 2,
      1: 1,
    },
  },
  {
    id: 4,
    name: "G-Cocid Medicine (450 mg)",
    category: "Herbal • Gm Ayurvedic Laboratories",
    originalPrice: 550,
    discountedPrice: 490,
    discount: "20% OFF",
    stockStatus: "In Stock",
    image: "/assets/products/product-4.png",
    images: [
      "/assets/products/product-4.png",
      "/assets/products/product-3.png",
      "/assets/products/product-2.png",
      "/assets/products/product-5.png",
    ],
    rating: 4.1,
    totalReviews: 67,
    salesCount: 1456,
    ratingDistribution: {
      5: 35,
      4: 18,
      3: 9,
      2: 3,
      1: 2,
    },
  },
  {
    id: 5,
    name: "Dianum",
    description: "(ডায়ানুম) 500 mg",
    category: "Herbal-Index Medicine",
    originalPrice: 550,
    discountedPrice: 450,
    discount: "20% OFF",
    stockStatus: "In Stock",
    image: "/assets/products/product-5.png",
    images: [
      "/assets/products/product-5.png",
      "/assets/products/product-1.png",
      "/assets/products/product-4.png",
      "/assets/products/product-6.png",
    ],
    rating: 4.3,
    totalReviews: 94,
    salesCount: 2134,
    ratingDistribution: {
      5: 58,
      4: 22,
      3: 10,
      2: 3,
      1: 1,
    },
  },
  {
    id: 6,
    name: "Bronchomu M (100 mL)",
    category: "Herbal • Optimum Pharmaceuticals",
    originalPrice: 550,
    discountedPrice: 450,
    discount: "20% OFF",
    stockStatus: "In Stock",
    image: "/assets/products/product-6.png",
    images: [
      "/assets/products/product-6.png",
      "/assets/products/product-2.png",
      "/assets/products/product-3.png",
      "/assets/products/product-5.png",
    ],
    rating: 4.6,
    totalReviews: 156,
    salesCount: 3247,
    ratingDistribution: {
      5: 108,
      4: 32,
      3: 12,
      2: 3,
      1: 1,
    },
  },
  {
    id: 7,
    name: "G-Cosef Medicine (450 ML)",
    category: "Herbal • Gm Ayurvedic Laboratories",
    originalPrice: 1100,
    discountedPrice: 910,
    discount: "20% OFF",
    stockStatus: "Stock Out",
    image: "/assets/products/product-3.png",
    images: [
      "/assets/products/product-3.png",
      "/assets/products/product-1.png",
      "/assets/products/product-4.png",
      "/assets/products/product-6.png",
    ],
  },
  {
    id: 8,
    name: "Spirulina Capsule (60 Cap)",
    category: "Herbal • Gm Ayurvedic Laboratories",
    originalPrice: 550,
    discountedPrice: 490,
    discount: "20% OFF",
    stockStatus: "In Stock",
    image: "/assets/products/product-1.png",
    images: [
      "/assets/products/product-1.png",
      "/assets/products/product-2.png",
      "/assets/products/product-5.png",
      "/assets/products/product-6.png",
    ],
  },
];
